### ISSUE TITLE
Invalid value definition when using constant expressions

### ISSUE THREAD

**Issue by BenMorel** [ApiGen/ApiGen#621]
PHP 5.6 supports [constant expressions](http://php.net/manual/en/migration56.new-features.php), but ApiGen fails with _Invalid Value Definition_ when using string concatenation in constants:

```
const VALUE = 'foo' . 'bar';
```

**Comment by TomasVotruba** [comment]
Resolved via #726

**Comment by StormBytePP** [comment]
This one is still failing for me in code such as:
class A {
      const TMPDIR = __DIR__."/../../../tmp";
}

Can you reopen?

**Comment by TomasVotruba** [comment]
Sure, I will make sure to look on that after reflection switch.

Thanks for providing failing code snippet :+1:

**Comment by TomasVotruba** [comment]
Probably missing support at [BetterReflection](https://github.com/roave/BetterReflection)

- `CompileNodeToValue::__invoke()`

Add in the end sth like:

```php
if ($node instanceof Node\Scalar\MagicConst\Dir) {
    return $this->compileDirConstant($node, $context);
}
```

**Comment by TomasVotruba** [comment]
Fix in progress: https://github.com/Roave/BetterReflection/pull/280

**Comment by TomasVotruba** [comment]
And done!
