### ISSUE TITLE
Is there possibility to generate API of another repository?

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#912]
Basically, I have directories like `/git/vendor/repo` and inside a PHP library in `src` dir. And what I need is to generate API for all repositories together. How to solve this use case?

If I create a directory somewhere and install ApigGen via composer with the following `composer.json`:

```
{
	"require": {
		"apigen/apigen": "5.0.0-RC1",
	},
	"minimum-stability": "dev",
	"autoload": {
		"classmap": ["/git/myvendor/localization/src", "...."]
	},
	"scripts": {
		"apigen": [
			"rm -rf ./docs/*",
			"vendor/bin/apigen generate /git/myvendor/localization/src /git/myvendor/..... --destination docs"
		]
	}
}
```

it fails for dependencies are not autoloaded or are different from the dependencies used by ApiGen (typically `nette/utils` - my library needs `3.0`, ApiGen uses `2.4`).

Any tips here?

**Comment by TomasVotruba** [comment]
For these use cases, use `composer create-project ...` approach.

Here is example of how to: https://github.com/nette/application/pull/182/commits/b6cb107128534012577f8d71b22d37bc3a0173fb

**Comment by vlastavesely** [comment]
And what about autoload of classes outside the source?

I just tested it in a way you suggested but it failed on my class extending `Nette\Security\User` that could not be autoloaded for it is not in `src` directory from which I generate the API.

```
  [ApiGen\Exception\Templating\FailedRenderFileException]                      
  Rendering of "/home/*/api/apigen/packages/ModuarConfiguration/src/Option/../../../../packages/ThemeDefault/src/class.latte" template to "/home/*/api/docs/class-Andromeda.Authorization.User.html" file failed due to: Roave\BetterReflection\Reflection\ReflectionClass "Nette\Security\User" could not be found in the located source   
```

**Comment by TomasVotruba** [comment]
Interesting. This might be caused by missing locator for `BetterReflection`. Could send a test case for class i `/src` with missing class in it? I'll investigate.

**Comment by vlastavesely** [comment]
1) installed Apigen
```
composer create-project apigen/apigen -s dev
```

2) placed this  into `src`

```
<?php

namespace Test;

use Nette;

class User extends Nette\Security\User
{

}
```

3) run
```
apigen/bin/apigen generate src --destination docs
```

4) Get the exception

**Comment by TomasVotruba** [comment]
Could you send that to PR?

**Comment by TomasVotruba** [comment]
Resolved by #915

**Comment by nelson6e65** [comment]
I'm still not able to build my project :disappointed: 

```
nelson6e65:~/workspace/php_nml (master) $ apigen generate src --destination output/api -vvv
PHP Notice:  Uninitialized string offset: 0 in /home/ubuntu/.composer/vendor/composer/ClassLoader.php on line 375

Notice: Uninitialized string offset: 0 in /home/ubuntu/.composer/vendor/composer/ClassLoader.php on line 375

                                                                                               
  [Roave\BetterReflection\Reflector\Exception\IdentifierNotFound]                              
  Roave\BetterReflection\Reflection\ReflectionClass "" could not be found in the located sour  
  ce                                                                                           
                                                                                               

Exception trace:
 () at /home/ubuntu/.composer/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:31
 Roave\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier() at /home/ubuntu/.composer/vendor/roave/better-reflection/src/Reflector/ClassReflector.php:55
 Roave\BetterReflection\Reflector\ClassReflector->reflect() at /home/ubuntu/.composer/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:680
 Roave\BetterReflection\Reflection\ReflectionClass->getParentClass() at /home/ubuntu/.composer/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1089
 Roave\BetterReflection\Reflection\ReflectionClass->getInheritanceClassHierarchy() at /home/ubuntu/.composer/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:919
 Roave\BetterReflection\Reflection\ReflectionClass->getInterfaces() at /home/ubuntu/.composer/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:947
 Roave\BetterReflection\Reflection\ReflectionClass->getInterfaceNames() at /home/ubuntu/.composer/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:1009
 Roave\BetterReflection\Reflection\ReflectionClass->implementsInterface() at /home/ubuntu/workspace/php_nml/vendor/apigen/apigen/packages/Reflection/src/Reflection/Class_/ClassReflection.php:177
 ApiGen\Reflection\Reflection\Class_\ClassReflection->implementsInterface() at /home/ubuntu/.composer/vendor/apigen/apigen/packages/Element/src/ReflectionCollector/NamespaceReflectionCollector.php:45
 ApiGen\Element\ReflectionCollector\NamespaceReflectionCollector->processReflection() at /home/ubuntu/.composer/vendor/apigen/apigen/packages/Element/src/ReflectionCollectorCollector.php:24
 ApiGen\Element\ReflectionCollectorCollector->processReflection() at /home/ubuntu/.composer/vendor/apigen/apigen/packages/Reflection/src/TransformerCollector.php:76
 ApiGen\Reflection\TransformerCollector->transformSingle() at /home/ubuntu/.composer/vendor/apigen/apigen/packages/Reflection/src/TransformerCollector.php:42
 ApiGen\Reflection\TransformerCollector->transformGroup() at /home/ubuntu/.composer/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:99
 ApiGen\Reflection\Parser\Parser->transformBetterClassInterfaceAndTraitReflections() at /home/ubuntu/.composer/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:105
 ApiGen\Reflection\Parser\Parser->parseClassElements() at /home/ubuntu/.composer/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:55
 ApiGen\Reflection\Parser\Parser->parseDirectories() at /home/ubuntu/.composer/vendor/apigen/apigen/src/Application/ApiGenApplication.php:55
 ApiGen\Application\ApiGenApplication->runCommand() at /home/ubuntu/.composer/vendor/apigen/apigen/src/Console/Command/GenerateCommand.php:61
 ApiGen\Console\Command\GenerateCommand->execute() at /home/ubuntu/.composer/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /home/ubuntu/.composer/vendor/symfony/console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at /home/ubuntu/.composer/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at /home/ubuntu/.composer/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at /home/ubuntu/.composer/vendor/apigen/apigen/bin/apigen:16

generate [--destination DESTINATION] [--] <source> (<source>)...
```

See #935

**Comment by vlastavesely** [comment]
> ` Roave\BetterReflection\Reflection\ReflectionClass "" could not be found in the located sour  
  ce `

Looks to me like a typo in your code.
Or do you have an anonymous class in your code? Like this:
```php
$something = new class {
    $nothing = 'something';
};
```

It seems it is not supported by BetterReflection that is being used in the ApiGen: Roave/BetterReflection#279

**Comment by TomasVotruba** [comment]
@nelson6e65 Always try to narrow down the source you're using. That way, we can detect code that is causing this. Without that it's only blindshooting.

```bash
apigen generate src/Directory/Subdirectory
```

**Comment by nelson6e65** [comment]
I'll try to restrict to a directory.

> Or do you have an anonymous class in your code?

Hmm... I don't. Only using an alias: 
https://github.com/nelson6e65/php_nml/blob/master/src/Extensions/String.php#L23

**Comment by nelson6e65** [comment]
**`apigen generate src/Extensions --destination output/api`**
```

                                                                                               
  [Roave\BetterReflection\Reflector\Exception\IdentifierNotFound]                              
  Roave\BetterReflection\Reflection\ReflectionClass "Cake\Utility\Text" could not be found in  
   the located source                                                                          
```                                         

**I thinks it takes `php_nml/src` as root of project and did not found the `php_nml/src/vendor/...`?**

Because when I run from vendor/bin a got another unrelated of error from that class:
**`vendor/bin/apigen generate src/Extensions --destination output/api`**
```
 1/7 [====>-----------------------]  14% < 1 sec/< 1 sec 18.0 MiB
                                                                                               
  [ApiGen\Exception\Templating\FailedRenderFileException]                                      
  Rendering of "/home/ubuntu/workspace/php_nml/vendor/apigen/apigen/packages/ModularConfigura  
  tion/src/Option/../../../../packages/ThemeDefault/src/class.latte" template to "/home/ubunt  
  u/workspace/php_nml/output/api/class-NelsonMartell.Extensions.Text.html" file failed due to  
  : "\https://www.ietf.org/rfc/rfc4122.txt" is not a valid Fqsen.

```
